#! /usr/bin/env bash

stpth=$PWD
outpth="$stpth/results"

rm -R $outpth
mkdir $outpth
cd $outpth
mkdir r r2 n bar j
cd $stpth/data

iter=0
for i in ./S* ; do
    cd $i
    for j in ./sample* ; do
	cd $j
	echo $iter > results_id
	mv total_dR2*.dat $outpth/rr/rr_$iter.dat
	mv total_dR*.dat $outpth/r/r_$iter.dat
	mv total_N*.dat $outpth/n/n_$iter.dat
	cp total_bar.dat $outpth/bar/bar_$iter.dat
	mv total_bar.dat $outpth/j/j_$iter.dat

	((iter++))
	cd ..
    done
    cd ..
echo $i $iter
done

cd $stpth