#! /usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"
PTH=$( dirname "$SOURCE" )
SRC=$PTH

stpth=$PWD
cd $stpth/data
src_file=$stpth/data/bad_data
rm -f $src_file

#echo $0 > tmp
#echo $PWD >> tmp
#echo $SRC >> tmp

for i in ./S* ; do
    cd $i
    iter=0
    for j in ./sample* ; do
	((iter++))
	echo $iter
	cd $j
	$SRC/com_files ${src_file}
	cd ..
    done
    cd ..
done

cd $stpth