#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
PTH=$( dirname "$SOURCE" )
SRC="$PTH/tools"

#echo "$0" > tmp
#echo $PWD >> tmp
#echo $SRC >> tmp
echo $1
$SRC/combine "$1"
$SRC/collect

#./integrate
#./static_avg
#./static_loop
