#! /usr/bin/env bash

stpth=$PWD
outpth="$stpth/results"

rm -R $outpth
mkdir $outpth
cd $outpth
mkdir R R2
cd $stpth/data

iter=0
for i in ./S* ; do
    cd $i
    for j in ./sample* ; do
	cd $j
	echo $iter > results_id
	mv total_dR.dat $outpth/R/r_$iter.dat
	mv total_dR2.dat $outpth/R2/r2_$iter.dat
	((iter++))
	cd ..
    done
    cd ..
echo $i $iter
done

cd $stpth