#!/bin/bash



echo "Sredniuje..."

module load python-numpy



stpth=$PWD

lista=`ls S*static.r2`
min="half"
max="last"
every=1
./static_mean.py $min $max "f_tracer_m.dat" $lista

lista=`ls S*static.r`
min="half"
max="last"
every=1
./static_mean.py $min $max "f_coll_m.dat" $lista
