#!/bin/bash



echo "Sredniuje..."

module load python-numpy



stpth=$PWD

lista=`ls *loop.rr`
min="half"
max="last"
every=1
./static_mean.py $min $max "f_tracer.dat" $lista

lista=`ls *loop.r`
min="half"
max="last"
every=1
./static_mean.py $min $max "f_coll.dat" $lista
